# Generated by Django 5.0.6 on 2024-07-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('favorite', models.BooleanField(default=False)),
                ('month', models.CharField(blank=True, choices=[('jan', 'January'), ('feb', 'February'), ('marc', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('july', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], default='jan', max_length=12)),
            ],
        ),
    ]
